name: Build and publish Docker image
on:
  push:
    tags:
      - "*"
jobs:
  deploy:
    name: Build & push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: "mimir/website"
          tags: |
            type=raw,value={{ref}},event=push

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: cr.liplum.net
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
